#!/usr/bin/env python3
"""
Computes and writes the concentric-ring conjecture status badge.

Six raw fields (in each conjecture's frontmatter `status:` block) are the
single source of truth. This script derives two grades from them and
renders a self-contained inline SVG badge plus a plain-English caption.
Never hand-edit `status_badge:` -- it is regenerated by this script.

    statement_informal  ai | human
    statement_formal    open | ai | human
    statement_match     open | ai | human
    proof_informal      open | ai | human
    proof_review        ai | human            (vacuous once proof_formal != open)
    proof_formal        open | ai | human

Dependency constraints (checked by validate()):
    statement_match  != open  requires  statement_formal != open
    proof_formal     != open  requires  statement_formal != open

Grading functions
------------------
sigma(s1, s2, s3) -- statement grade, 0..5:
    s2 == open                -> 1 if s1 == human else 0
    s2 != open, s3 == open    -> 2
    s2 != open, s3 == ai      -> 3
    s2 != open, s3 == human   -> 4 + (1 if s1 == human else 0)   # 4 or 5

pi(p1, p2, p3) -- proof grade, 0..4:
    p3 != open                -> 4
    p3 == open, p1 == open    -> 0
    otherwise                 -> 1 + (p1 == human) + (p2 == human)   # 1, 2, 3

pi ignores who wrote a *formal* proof (AI vs human): once there is a
machine-checked proof object, the kernel is the arbiter (de Bruijn
criterion), so proof_formal authorship is metadata/caption text, not a
colour.

Seal (de Bruijn-complete): pi == 4 and sigma >= 4.
"""

import re
import sys
from pathlib import Path

LEVELS3 = ("open", "ai", "human")
LEVELS2 = ("ai", "human")

FIELD_SPECS = {
    "statement_informal": LEVELS2,
    "statement_formal": LEVELS3,
    "statement_match": LEVELS3,
    "proof_informal": LEVELS3,
    "proof_review": LEVELS2,
    "proof_formal": LEVELS3,
}
FREE_TEXT_FIELDS = ("statement_by", "proof_by")

START_MARKER = "<!-- status:start -->"
END_MARKER = "<!-- status:end -->"


def compute_sigma(s1, s2, s3):
    if s2 == "open":
        return 1 if s1 == "human" else 0
    if s3 == "open":
        return 2
    if s3 == "ai":
        return 3
    return 4 + (1 if s1 == "human" else 0)


def compute_pi(p1, p2, p3):
    if p3 != "open":
        return 4
    if p1 == "open":
        return 0
    return 1 + (1 if p1 == "human" else 0) + (1 if p2 == "human" else 0)


def validate(status, filename):
    for field, allowed in FIELD_SPECS.items():
        if field not in status:
            raise ValueError(f"{filename}: missing status.{field}")
        if status[field] not in allowed:
            raise ValueError(
                f"{filename}: status.{field} = {status[field]!r} not in {allowed}"
            )
    if status["statement_match"] != "open" and status["statement_formal"] == "open":
        raise ValueError(
            f"{filename}: statement_match={status['statement_match']!r} requires "
            f"statement_formal != open (nothing to match against)"
        )
    if status["proof_formal"] != "open" and status["statement_formal"] == "open":
        raise ValueError(
            f"{filename}: proof_formal={status['proof_formal']!r} requires "
            f"statement_formal != open (a formal proof is a proof of a formal statement)"
        )


_DASH = {"open": "1,3", "ai": "5,3", "human": None}
_GLYPH = {0: "–", 1: "·", 2: "•", 3: "●", 4: "✓"}

_LABEL = {"open": "none yet", "ai": "AI", "human": "human"}

# A full absolute URL, not a relative or root-relative ('/...') path.
# Two things rule those out: (1) Quarto's HTML post-processing rewrites
# root-relative hrefs inside raw embedded HTML incorrectly (turns
# '/open-problems/index.html' into '../open-problems/index.html', a 404);
# (2) the SAME status_badge string this script writes into a conjecture's
# frontmatter is also reused verbatim by Quarto's listing table on that
# conjecture's (shallower) topic-listing page, so no single relative path
# can be correct in both places at once. An absolute URL is immune to
# both problems since it's never relative-resolved.
#
# Trade-off: clicking a badge under `quarto preview` jumps to the live
# production site rather than the local preview.
LEGEND_URL = "https://crypto-conjura.github.io/open-problems/status-legend/index.html#status-legend"


def render_badge_svg(status, legend_url=LEGEND_URL):
    sigma = compute_sigma(
        status["statement_informal"], status["statement_formal"], status["statement_match"]
    )
    pi = compute_pi(status["proof_informal"], status["proof_review"], status["proof_formal"])
    sealed = pi == 4 and sigma >= 4

    dash = _DASH[status["statement_match"]]
    dash_attr = f" stroke-dasharray='{dash}'" if dash else ""
    seal_el = (
        "<circle cx='16' cy='16' r='15' fill='none' stroke-width='1.5' class='cj-seal'/>"
        if sealed
        else ""
    )
    glyph = _GLYPH[pi]
    title = render_caption(status)

    # NOTE: attribute values use single quotes throughout, matching the
    # site's convention for HTML embedded in a double-quoted YAML string
    # (see e.g. the cj-badge spans elsewhere) -- double quotes here would
    # prematurely terminate the YAML string value.
    svg = (
        "<svg class='cj-status-badge' viewBox='0 0 32 32' width='28' height='28' "
        "xmlns='http://www.w3.org/2000/svg' role='img'>"
        f"<title>{title}</title>"
        f"{seal_el}"
        f"<circle cx='16' cy='16' r='13' fill='none' stroke-width='4' "
        f"class='cj-ring-{sigma}'{dash_attr}/>"
        f"<circle cx='16' cy='16' r='8' class='cj-disc-{pi}'/>"
        f"<text x='16' y='17' text-anchor='middle' dominant-baseline='central' "
        f"class='cj-glyph' font-size='9'>{glyph}</text>"
        "</svg>"
    )
    # Wrapped in a link to the legend so the symbol itself is clickable --
    # aria-label repeats the caption since a screen reader announces link
    # text, not the SVG <title>, for an anchor-wrapped image.
    return (
        f"<a href='{legend_url}' class='cj-status-link' aria-label='{title} "
        "Click for the status badge legend.'>"
        f"{svg}"
        "</a>"
    )


def render_caption(status):
    s1, s2, s3 = status["statement_informal"], status["statement_formal"], status["statement_match"]
    p1, p2, p3 = status["proof_informal"], status["proof_review"], status["proof_formal"]

    if s2 == "open":
        stmt = f"Statement: {_LABEL[s1]}-written, not yet formalized."
    else:
        stmt = f"Statement: {_LABEL[s1]}-written, {_LABEL[s2]}-formalized"
        if s3 == "open":
            stmt += ", not yet matched against the informal statement."
        else:
            stmt += f", {_LABEL[s3]}-matched against the informal statement."

    if p3 != "open":
        proof = f"Proof: machine-checked ({_LABEL[p3]}-formalized)."
    elif p1 == "open":
        proof = "Proof: open -- no attempt yet."
    else:
        # proof_review is a 2-level field (ai|human) whose floor ("ai") means
        # "not yet reviewed by a human" -- it does NOT assert that an AI
        # reviewer actually looked at it, only that no human has. Only say
        # "reviewed" once a human actually has; otherwise say so plainly.
        review = "human-reviewed" if p2 == "human" else "not yet independently reviewed"
        proof = f"Proof: {_LABEL[p1]} draft, {review}, not yet formalized."

    return f"{stmt} {proof}"


def self_test():
    checked = 0
    for s1 in LEVELS2:
        for s2 in LEVELS3:
            for s3 in LEVELS3:
                if s3 != "open" and s2 == "open":
                    continue
                for p1 in LEVELS3:
                    for p2 in LEVELS2:
                        for p3 in LEVELS3:
                            if p3 != "open" and s2 == "open":
                                continue
                            base = dict(
                                statement_informal=s1,
                                statement_formal=s2,
                                statement_match=s3,
                                proof_informal=p1,
                                proof_review=p2,
                                proof_formal=p3,
                            )
                            sigma0 = compute_sigma(s1, s2, s3)
                            pi0 = compute_pi(p1, p2, p3)
                            for field, levels in FIELD_SPECS.items():
                                idx = levels.index(base[field])
                                if idx + 1 >= len(levels):
                                    continue
                                raised = dict(base)
                                raised[field] = levels[idx + 1]
                                if (
                                    raised["statement_match"] != "open"
                                    and raised["statement_formal"] == "open"
                                ):
                                    continue
                                if (
                                    raised["proof_formal"] != "open"
                                    and raised["statement_formal"] == "open"
                                ):
                                    continue
                                sigma1 = compute_sigma(
                                    raised["statement_informal"],
                                    raised["statement_formal"],
                                    raised["statement_match"],
                                )
                                pi1 = compute_pi(
                                    raised["proof_informal"],
                                    raised["proof_review"],
                                    raised["proof_formal"],
                                )
                                assert sigma1 >= sigma0, (base, field, sigma0, sigma1)
                                assert pi1 >= pi0, (base, field, pi0, pi1)
                            checked += 1
    print(f"self-test OK: {checked} constraint-valid tuples, monotone in every field")


_STATUS_BLOCK_RE = re.compile(
    r"^status:\s*\n((?:[ \t]+\S.*\n?)+)", re.MULTILINE
)
_KV_RE = re.compile(r"^[ \t]+([A-Za-z_]+):\s*(.*)$")


def parse_status_block(frontmatter, filename):
    m = _STATUS_BLOCK_RE.search(frontmatter)
    if not m:
        return None
    status = {}
    for line in m.group(1).splitlines():
        kv = _KV_RE.match(line)
        if not kv:
            continue
        key, val = kv.group(1), kv.group(2).strip()
        if val.startswith('"') and val.endswith('"'):
            val = val[1:-1]
        status[key] = val
    for field in FIELD_SPECS:
        if field not in status:
            raise ValueError(f"{filename}: status block missing '{field}'")
    for field in FREE_TEXT_FIELDS:
        status.setdefault(field, "")
    return status


def process_file(path):
    text = path.read_text(encoding="utf-8")
    fm_match = re.match(r"^---\n(.*?\n)---\n", text, re.DOTALL)
    if not fm_match:
        return False
    frontmatter = fm_match.group(1)

    status = parse_status_block(frontmatter, path)
    if status is None:
        return False

    validate(status, str(path))
    badge = render_badge_svg(status)
    caption = render_caption(status)

    new_frontmatter = re.sub(r"^status_badge:.*\n?", "", frontmatter, flags=re.MULTILINE)
    badge_line = f'status_badge: "{badge}"'
    new_frontmatter = new_frontmatter.rstrip("\n") + "\n" + badge_line + "\n"

    new_text = text[: fm_match.start(1)] + new_frontmatter + text[fm_match.end(1) :]

    body_block = f"{START_MARKER}\n{badge}\n\n*{caption}*\n{END_MARKER}"
    marker_re = re.compile(
        re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER), re.DOTALL
    )
    if not marker_re.search(new_text):
        raise ValueError(
            f"{path}: no {START_MARKER} ... {END_MARKER} markers found in body"
        )
    new_text = marker_re.sub(body_block, new_text)

    if new_text != text:
        path.write_text(new_text, encoding="utf-8")
        print(f"updated {path}")
        return True
    return False


def main(argv):
    if "--self-test" in argv:
        self_test()
        return 0

    targets = [a for a in argv if not a.startswith("--")] or ["open-problems"]
    files = []
    for t in targets:
        p = Path(t)
        if p.is_dir():
            files.extend(sorted(p.glob("**/index.qmd")))
        elif p.is_file():
            files.append(p)

    changed = 0
    for f in files:
        if process_file(f):
            changed += 1
    print(f"{changed} file(s) updated out of {len(files)} scanned")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
